### ISSUE TITLE
Type identifier concatenation

### ISSUE THREAD

**Issue by photex** [sjames/cycloneddscodegen#1]
https://github.com/sjames/cycloneddscodegen/blob/091c293a08c046e8ea1f5aa024e0ac27ccf6285d/src/lib.rs#L226

Was perusing the code here and saw the comment. Have you seen https://github.com/dtolnay/paste?

**Comment by sjames** [comment]
thanks @photex, I will take a look. I think I may have tried it and faced some issue.  I'll have to think about it.
